### ISSUE TITLE
Offensive text in countries list

### ISSUE THREAD

**Issue by fifieldt** [hotosm/iso-countries-languages#3]
Recently it was noted that the list of countries in HOT Tasking Manager user profile settings contained text that residents of Taiwan consider highly offensive.

I traced the Tasking Manager's code to this library where, indeed, the default ISO 3166-1 label for Taiwan that angers users is found.

I've seen two fixes for this in other libraries:
1) Simply remove the extraneous "Province of China" text
2) Keep the ISO 3166-1 names in place, but implement a "human readable" version of names that are a bit unwieldy and default to that when displaying

see eg https://github.com/SmileyChris/django-countries/issues/60 and its list:

COMMON_NAMES = {
    "BN": _("Brunei"),
    "BO": _("Bolivia"),
    "IR": _("Iran"),
    "KP": _("North Korea"),
    "KR": _("South Korea"),
    "LA": _("Laos"),
    "MD": _("Moldovia"),
    "RU": _("Russia"),
    "SY": _("Syria"),
    "TW": _("Taiwan"),
    "TZ": _("Tanzania"),
    "VE": _("Venezuela"),
    "VN": _("Vietnam"),
}

**Comment by willemarcel** [comment]
Thanks, @fifieldt! Sorry for the delay on answering. I switched the countries data to OpenStreetMap ( #5 ). It's fixed now.

**Comment by fifieldt** [comment]
Thanks @willemarcel , I confirm it's updated in the tasking manager.
